config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :tasks, only: [ :new, :create, :destroy, :edit, :update ]
  end

  namespace :api do
    resources :projects, only: [] do
      resources :tasks, only: [ :index ]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  validates :title, presence: true

  STATUSES = %w[todo in_progress done].freeze

  validates :status,
    presence: true,
    inclusion: { in: STATUSES }

  VALID_PRIORITIES = (1..5).to_a

  validates :priority, presence: true, inclusion: { in: VALID_PRIORITIES }

  # Class method (so logic is only written once)
  def self.overdue_query
    where("due_date IS NOT NULL AND due_date < ? AND status != ?", Date.current, "done")
  end

  # Instance method
  def overdue?
    self.class.overdue_query.where(id: id).exists?
  end

  # Scope
  scope :overdue, -> { overdue_query }
  scope :with_status, ->(status) { where(status: status) }
  scope :sorted_by, ->(sort_param) {
    # Asc/desc switched because lowest priority is the highest.
    order_clause = case sort_param
    when "priority_desc" then { priority: :asc }
    when "priority_asc"  then { priority: :desc }
    when "due_desc"      then { due_date: :desc }
    when "due_asc"       then { due_date: :asc }
    else {}
    end
    order(order_clause)
  }
end

app/controllers/api/tasks_controller.rb
module Api
  class TasksController < ApplicationController
    # json only route
    def index
        project = Project.find(params[:project_id])

        # Start with all tasks for this project
        tasks = project.tasks

        # Status filter
        if params[:status].present?
          tasks = tasks.with_status(params[:status])
        end

        # Overdue
        if params[:overdue].present?
          tasks = tasks.overdue if params[:overdue] == "true"
        end

        # Render JSON
        render json: tasks.map { |task|
          {
            id: task.id,
            title: task.title,
            status: task.status,
            priority: task.priority,
            due_date: task.due_date,
            overdue: task.overdue?
          }
        }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    # IDK if its bad or "not rails-y" to query database direct... just seems faster for lg sets.
    @projects = Project
      .left_joins(:tasks)
      .select(
        "projects.*,
        COUNT(tasks.id) AS tasks_count,
        COUNT(
          CASE
            WHEN tasks.status IN ('todo', 'in_progress')
            THEN 1
          END
        ) AS unf_tasks_count"
      )
      .group("projects.id")
  end

  # GET /projects/1 or /projects/1.json
  def show
    # update on friendly branch
    @project = Project.find(params[:id])
    @tasks = @project.tasks

    if params[:status].present?
      @tasks = @tasks.with_status(params[:status])
    end

    if params[:sort].present?
      @tasks = @tasks.sorted_by(params[:sort])
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_path, notice: "Project was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.expect(project: [ :name, :description ])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: [ :destroy, :edit, :update, :show ]

  def show
    @task = Task.find(params[:id])
  end

  # Nested project routes
  def new
    @task = @project.tasks.new
  end

  def create
    @task = @project.tasks.new(task_params)
    Rails.logger.info "Creating task with params: #{task_params.inspect}"


    if @task.save
      Rails.logger.info "Task saved successfully"
      redirect_to @project, notice: "Task created successfully!"
    else
      # render the same form with errors
      Rails.logger.info "@task class: #{@task.class.name}, errors: #{@task.errors.full_messages.inspect}"
      render :new
    end
  end

  # GET /projects/1/edit
  def edit
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @project, notice: "Task was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to @project, notice: "Task was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end


  def task_params
    params.require(:task).permit(:title, :description, :status, :due_date, :priority)  # add other fields as needed
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title><%= content_for(:title) || "Hi Ea Task Track" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Hi Ea Task Track">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">


    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<body>
    <%= yield %>
</body>

</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
<% if project.errors.any? %>
<div class="alert alert-danger" role="alert">
    <%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:
    <ul>
        <% project.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
</div>

<div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description, class: "form-control" %>
</div>

<div>
    <%= form.submit %>
</div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
    <div>
        <strong>Project Name:</strong>
        <%= project.name %>
    </div>
</div>

app/views/projects/edit.html.erb
<% content_for :title, "Editing project" %>

<div class="container">
    <%= link_to "<< Back to projects", projects_path %>
    <div class="column">
        <div class="row">
            <h1>Editing project</h1>
            <%= render "form", project: @project %>
            <br>
            <div>
                <%= link_to "<< Back to projects", projects_path %>
            </div>
        </div>
    </div>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Projects" %>

<div class="container">
    <div class="column">
        <div class="row">
            <h1>Projects</h1>
            <%= link_to "New project", new_project_path, class: "btn btn-primary" %>
        </div>
        <br>
        <div class="row">
            <div id="projects">
                <% @projects.each do |project| %>
                <%= render project %>
                <div>
                    <strong>Number of Tasks:</strong>
                    <%= project.tasks_count %>
                </div>
                <div>
                    <strong>Number of Unfinished Tasks:</strong>
                    <%= project.unf_tasks_count %>
                </div>
                <p>
                    <%= link_to "View", project, class: "btn btn-primary" %>
                </p>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/projects/new.html.erb
<% content_for :title, "New project" %>

<div class="container">
    <%= link_to "<< Back to projects", projects_path %>
    <div class="column">
        <div class="row">
            <h1>New project</h1>
            <%= render "form", project: @project %>
            <br>
            <div>
                <%= link_to "<< Back to projects", projects_path %>
            </div>
        </div>
    </div>
</div>

app/views/projects/new_task.html.erb
<h1>New Task for <%= @project.name %></h1>

<%= form_with model: [@project, @task], url: create_task_project_path(@project), local: true do |f| %>
  <% if @task.errors.any? %>
    <div style="color: red;">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description, style: "display: block" %>
    <%= f.textarea :description %>
  </div>  

  <div>
    <%= f.label :status %>
    <%= f.select :status, Task::STATUSES.map { |s| [s.titleize, s] }, prompt: "Select status" %>
  </div>  

  <div>
    <%= f.label :due_date%>
    <%= f.date_select :due_date %>
  </div>  

  <div>
    <%= f.label :priority%>
    <%= f.select :priority, Task::VALID_PRIORITIES.map { |s| [s, s] }, prompt: "Select priority" %>
  </div>  

  <div>
    <%= f.submit "Create Task" %>
  </div>
<% end %>

<%= link_to "Back to Project", project_path(@project) %>

app/views/projects/show.html.erb
<div class="container">
    <%= link_to "<< Back to projects", projects_path %>

    <div class="column">
        <div class="row-p5">

            <p style="color: green"><%= notice %></p>
            <h3>
                <%= render @project %>
            </h3>
            <div>
                <strong>Description:</strong>
                <%= @project.description %>
            </div>
        </div>
        <br>
        <div class="row-p5">
            <%= link_to "Edit this project", edit_project_path(@project), class: "btn btn-primary" %>
            <%= link_to "Add new task to this project", new_project_task_path(@project), class: "btn btn-primary" %>
            <%= button_to "Destroy this project", @project, method: :delete, class: "btn btn-primary" %>
        </div>
        <br>
        <div class="row-p5">
            <div>
                <div id="tasks-filter">
                    <%= form_with url: project_path(@project), method: :get, local: true do %>
                    <!-- filter -->
                    <label for="status">Filter:</label>
                    <%= select_tag :status, 
                      options_for_select(Task::STATUSES, params[:status]),
                      include_blank: "All",
                      onchange: "this.form.submit()", class: "btn btn-light dropdown-toggle"%>

                    <!-- sort -->
                    <label for="sort">Sort by:</label>
                    <%= select_tag :sort,
                      options_for_select([["Priority (high → low)", "priority_desc"], ["Priority (low → high)", "priority_asc"], ["Due Date (soonest → latest)", "due_asc"], ["Due Date (latest → soonest)", "due_desc"]], params[:sort]),
                      include_blank: "Default",
                      onchange: "this.form.submit()", class: "btn btn-light dropdown-toggle" %>
                    <% end %>
                </div>
                <br>
                <!-- Tasks table, this could probably move to a partial if reuse was desired, maybe tasks#index but don't want that as an accessible route... -->
                <% if @tasks.any? %>
                <div>
                    <h4>Tasks</h4>
                    <table class="table">
                        <thead>
                            <tr>
                                <td class="h5">Title</td>
                                <td class="h5">Status</td>
                                <td class="h5">Priority</td>
                                <td class="h5">Due Date</td>
                            </tr>
                        </thead>
                        <tbody>
                            <div id="tasks">
                                <%= render @tasks %>
                            </div>
                        </tbody>
                    </table>
                </div>
                <% end %>


                <%= link_to "<< Back to projects", projects_path %>

            </div>

        </div>
    </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with model: [@project, @task], local: true, data: { turbo: false } do |f| %>     <!-- Using turbo: false here because errors don't show up otherwise, would replace with a precise turbo stream -->
<% if f.object.errors.any? %>
<div class="alert alert-danger" role="alert">
    <%= pluralize(f.object.errors.count, "error") %> prohibited this project from being saved:
    <ul>
        <% f.object.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
    </ul>
</div>
<% end %>



<div>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
</div>

<div>
    <%= f.label :description, style: "display: block" %>
    <%= f.textarea :description, class: "form-control"  %>
</div>

<div>
    <%= f.label :status %>
    <%= f.select :status, Task::STATUSES.map { |s| [s.titleize, s] }, prompt: "Select status", class: "btn btn-light dropdown-toggle"  %>
</div>

<div>
    <%= f.label :due_date%>
    <%= f.date_field :due_date, include_blank: true, class: "form-control"  %>
</div>

<div>
    <%= f.label :priority%>
    <%= f.select :priority, Task::VALID_PRIORITIES.map { |s| [s, s] }, prompt: "Select priority", class: "btn btn-light dropdown-toggle"  %>
</div>

<%= f.submit%>
</div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
    <tr>

        <td>
            <div class="d-flex flex-wrap gap-1">
                <div class="row g-2">
                    <div class="d-flex gap-2">
                        <h6><%= task.title %></h6>
                        <% if task.overdue? %>
                        <span class="badge text-bg-danger">Overdue</span>
                        <% end %>
                    </div>

                    <div class="d-flex gap-2">
                        <%= link_to "Edit", edit_project_task_path(@project, task), class: "btn btn-secondary" %>
                        <%= button_to "Delete", project_task_path(@project, task), method: :delete, class: "btn btn-secondary" %>
                    </div>

                    <div>
                        <!-- Carrot/dropdown reveal tab for view button to display task description -->
                        <details>
                            <summary class="view-link">View</summary>
                            <div class="task-description">
                                <!-- "None" if no description instead of blank -->
                                Task Description:
                                <p><%= task.description.present? ? task.description : "None" %></p>
                            </div>
                        </details>
                    </div>
                </div>
            </div>
        </td>


        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= task.due_date %></td>


    </tr>
</div>

app/views/tasks/edit.html.erb
<% content_for :title, "Editing task" %>

<div class="container">
    <%= link_to "<< Back to project", project_path(@project) %>

    <div class="column">
        <div class="row">

            <h1>Editing task</h1>

            <%= render "form", task: @task %>

            <br>

            <div>
                <%= link_to "<< Back to project", project_path(@project) %>
            </div>

        </div>
    </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
    <%= link_to "<< Back to project", project_path(@project) %>

    <div class="column">
        <div class="row">


            <h1>New Task for <%= @project.name %></h1>

            <%= render "form", task: @task %>


            <%= link_to "<< Back to Project", project_path(@project) %>

        </div>
    </div>
</div>